server:
  port: 8090
#  servlet:
#    context-path: /productsapi

spring:
  application:
    name: PSEUDO-SERVICE-MONGO
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
        use-new-id-generator-mappings: false
      database-platform: org.hibernate.dialect.MySQL8InnoDBDialect

  ribbon:
    ReadTimeout: 160000000
    ConnectTimeout: 160000000
